### ISSUE TITLE
Investigate if this could just be a problem matcher

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/jest-github-actions-reporter#2]
Not sure if problem matcher support multi-line regex well enough to match the default jest output, but might be worth investigating.

**Comment by dscho** [comment]
Here is a link to the relevant documentation: https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

**Comment by dscho** [comment]
From that documentation, it does not seem like multi-line messages are supported by the problem matchers...

**Comment by cschleiden** [comment]
@dscho Thanks for taking a look, closing this then for now. 🙇‍♂️

**Comment by peternewman** [comment]
For info this is possible now (but you're possibly aware of this already) https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md#multiline-matching

**Comment by dscho** [comment]
I was not aware of this! Exciting!

**Comment by peternewman** [comment]
Ah well now you know. I think I saw another jest problem matcher when I was searching, so you might find someone has superseded this.
