### ISSUE TITLE
Under which license is this?

### ISSUE THREAD

**Issue by florianschmidt1994** [cschleiden/jest-github-actions-reporter#7]
Hi @cschleiden :) 
Thanks for your great work with this reporter. I was planning to fork this and add some custom code for an internal build process, so I was wondering if would consider licensing this code?

**Comment by cschleiden** [comment]
@florianschmidt1994 Done! Happy forking :)

**Comment by florianschmidt1994** [comment]
That's amazing, thank you so much!
